import Foundation

/// One accumulated item of a rolling debrief: a decision, an action item, or
/// an open question, tracked in ONE shared id space across all three kinds so
/// a single `resolvedIds`/`corrections` id list (as the model sees it in
/// `DebriefState.rendered(language:)`) can reference any of them.
///
/// Items are never deleted by a model response — `resolved` is set instead —
/// so ids stay stable for the whole meeting and a delta that arrives late can
/// still reference an item the model saw several chunks ago.
struct DebriefItem: Identifiable, Codable, Equatable {
    enum Kind: String, Codable, Equatable {
        case decision
        case action
        case openQuestion
    }

    var id: Int
    var kind: Kind
    var text: String
    var owner: String?
    var due: String?
    /// Index of the transcript chunk this item first appeared in. Kept so a
    /// live "so far" view can show provenance and so dedupe can deterministically
    /// keep the EARLIER of two duplicates.
    var sourceChunk: Int
    var resolved: Bool

    /// Owner strings that name no one — the speaker-label scaffolding itself
    /// ("Them"), or its plural/pronoun equivalents. The chunk transcripts fed
    /// to a delta engine are labeled "Me:"/"Them:" paragraphs, so a model that
    /// half-follows the ownership rule writes the LABEL as the owner instead of
    /// leaving it null. These are stripped on top of
    /// `DebriefActionItem.genericOwnerPlaceholders` ("team", "everyone", …),
    /// which covers the generic-group case but not the label case, and which
    /// lives in Models/DebriefSummary.swift (owned by another story — not
    /// edited here).
    static let labelOwnerPlaceholders: Set<String> = [
        "them",
        "the others",
        "the other participant",
        "the other participants",
        "others",
        "dem",
        "de",
        "de andra",
        "den andra",
        "motparten",
        "motparterna"
    ]

    /// `owner`, with placeholder, generic-group, and speaker-label values
    /// mapped to nil.
    static func normalizedOwner(_ owner: String?) -> String? {
        DebriefActionItem.normalizedField(
            owner,
            extraPlaceholders: DebriefActionItem.genericOwnerPlaceholders.union(labelOwnerPlaceholders)
        )
    }

    init(
        id: Int,
        kind: Kind,
        text: String,
        owner: String? = nil,
        due: String? = nil,
        sourceChunk: Int,
        resolved: Bool = false
    ) {
        self.id = id
        self.kind = kind
        self.text = text
        self.owner = owner
        self.due = due
        self.sourceChunk = sourceChunk
        self.resolved = resolved
    }
}

/// The accumulated state of an in-progress rolling debrief: the item list that
/// Swift code owns (the model only ever proposes deltas against it), plus the
/// free-text summary paragraph, which IS fully regenerated by the model on
/// every chunk.
///
/// The asymmetry is deliberate and is the whole point of decision 8: summary
/// prose is cheap to lose and re-derive, an action item is not. The spike
/// showed naive rolling regeneration losing every action item by chunk 2,
/// while a code-side accumulator stayed monotone.
struct DebriefState: Equatable {
    /// How much of the state `rendered(language:)` shows the model.
    ///
    /// A long meeting's numbered state competes with the new chunk for the
    /// model's context window, and the state grows monotonically while the
    /// chunk does not — so the state is what has to shrink when a call comes
    /// back "too long". `.compact` is the retry render:
    /// `RollingDebriefSummarizer.ingest` re-issues a context-window failure
    /// against it before falling back to splitting the chunk.
    enum RenderStyle: Equatable {
        /// Summary paragraph, ids, text, owner and due.
        case full
        /// Ids and text only — no summary paragraph, no owner/due.
        case compact
    }

    /// Longest item text shown back to the model. An accumulated item is one
    /// sentence of intent; anything past this is transcription spill that costs
    /// context without changing which id the model points at. Only the MODEL's
    /// view is truncated — `items` and `toDebriefSummary()` keep the full text.
    static let maxRenderedItemCharacters = 160

    var summary: String
    var items: [DebriefItem]
    /// Next id to hand out. Monotonically increasing and never reused, even
    /// after a dedupe or drop removes an item.
    var nextId: Int
    /// Presentation only: which render `rendered(language:)` produces. Carried
    /// on the state because `DeltaSummarizing.extractDelta` takes the state and
    /// renders it internally, so this is how a caller asks for the smaller view
    /// without every engine growing a second entry point.
    var renderStyle: RenderStyle

    init(
        summary: String = "",
        items: [DebriefItem] = [],
        nextId: Int = 1,
        renderStyle: RenderStyle = .full
    ) {
        self.summary = summary
        self.items = items
        self.nextId = nextId
        self.renderStyle = renderStyle
    }

    /// A copy that renders in `.compact` style.
    func compacted() -> DebriefState {
        var copy = self
        copy.renderStyle = .compact
        return copy
    }

    /// Items not yet resolved, in insertion order.
    var activeItems: [DebriefItem] { items.filter { !$0.resolved } }

    func activeItems(ofKind kind: DebriefItem.Kind) -> [DebriefItem] {
        items.filter { !$0.resolved && $0.kind == kind }
    }

    /// Numbered plain-text rendering of the ACTIVE state, fed back to the model
    /// so the ids in its next delta (`resolvedIds`, `corrections`, `dropIds`)
    /// reference real items.
    ///
    /// Resolved items are omitted: the model should never re-resolve or correct
    /// something already closed. The scaffolding labels
    /// (SUMMARY SO FAR/DECISIONS/…) stay English regardless of `language`,
    /// matching the probe — they are structural markers for the model's
    /// context, not user-facing output; the field CONTENT stays in whatever
    /// language the model wrote it in. `language` is accepted so the signature
    /// does not have to change if a future engine needs localized scaffolding.
    func rendered(language: String) -> String {
        _ = language

        var lines: [String] = []
        if renderStyle == .full {
            lines.append("SUMMARY SO FAR:")
            lines.append(summary.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty ? "(none yet)" : summary)
            lines.append("")
        }
        lines.append("DECISIONS (numbered):")
        lines.append(Self.renderPlain(activeItems(ofKind: .decision)))
        lines.append("")
        lines.append("ACTION ITEMS (numbered):")
        let actions = activeItems(ofKind: .action)
        if actions.isEmpty {
            lines.append("(none)")
        } else {
            lines.append(actions.map { item -> String in
                var line = "[\(item.id)] \(Self.truncated(item.text))"
                guard renderStyle == .full else { return line }
                if let owner = item.owner { line += " | owner: \(owner)" }
                if let due = item.due { line += " | due: \(due)" }
                return line
            }.joined(separator: "\n"))
        }
        lines.append("")
        lines.append("OPEN QUESTIONS (numbered):")
        lines.append(Self.renderPlain(activeItems(ofKind: .openQuestion)))
        return lines.joined(separator: "\n")
    }

    private static func renderPlain(_ items: [DebriefItem]) -> String {
        items.isEmpty ? "(none)" : items.map { "[\($0.id)] \(truncated($0.text))" }.joined(separator: "\n")
    }

    /// `text` clipped to `maxRenderedItemCharacters`, with an ellipsis marking
    /// that it was clipped.
    static func truncated(_ text: String) -> String {
        guard text.count > maxRenderedItemCharacters else { return text }
        return String(text.prefix(maxRenderedItemCharacters)) + "…"
    }

    /// Projects the accumulated state into the app's existing output model.
    /// Resolved items are dropped here — they are kept in `items` only so ids
    /// stay stable and a "so far" view can still show what got closed.
    ///
    /// `normalized()` is applied so a placeholder owner/due an engine wrote
    /// instead of null (and the decision/action-item duplicate rule the app
    /// already enforces) is handled exactly as for a single-pass summary.
    func toDebriefSummary() -> DebriefSummary {
        DebriefSummary(
            summary: summary,
            decisions: activeItems(ofKind: .decision).map(\.text),
            actionItems: activeItems(ofKind: .action).map {
                // normalizedOwner, not just `normalized()` below: the app's own
                // normalization does not know about the "Me:"/"Them:" speaker
                // labels this path's chunks carry, so a literal "them" owner
                // would otherwise survive into the rendered ACTION ITEMS list.
                DebriefActionItem(text: $0.text, owner: DebriefItem.normalizedOwner($0.owner), due: $0.due)
            },
            openQuestions: activeItems(ofKind: .openQuestion).map(\.text)
        ).normalized()
    }
}
